# Liquidity Digital Recommendation Engine

<img src="files/DRE_NEW.jpeg">

In [ ]:
pip install sklearn

In [ ]:
pip install pandas

In [22]:
import ipywidgets as widgets
from ipywidgets import HBox, VBox
from IPython.display import display
from ipywidgets import IntProgress
from ipywidgets import interact, interact_manual
import pandas as pd 
import time

metadata = pd.read_csv('investor_activity.csv')
metadata

,investor,issuance_type,region,industry
0,TURNLING,"['STO', 'equity', 'debt']",Louisiana,"['finance', 'blockchain', 'technology']"
1,EMERGENT,"['debt', 'convertible note', 'debt']",Northern Mariana Islands,"['healthcare', 'consumer staples', 'technology']"
2,IRACK,"['convertible note', 'equity']",Mississippi,"['utilities', 'blockchain']"
3,MICRONAUT,"['equity', 'investment fund', 'convertible note']",American Samoa,"['blockchain', 'materials', 'utilities']"
4,TEMORAK,['equity'],Colorado,['blockchain']
...,...,...,...,...
358,ENTROFLEX,"['investment fund', 'equity']",Palau,"['security', 'agriculture']"
359,CINESANCT,"['investment fund', 'debt']",District Of Columbia,"['security', 'delivery']"
360,EXOTECHNO,"['equity', 'debt', 'investment fund']",Michigan,"['fashion', 'insurance', 'security']"
361,SPRINGBEE,['debt'],Pennsylvania,['delivery']
362,SCHOOLIO,"['investment fund', 'equity']",Oklahoma,"['security', 'agriculture']"

In [37]:
output = widgets.Output()

ALL = 'All regions'
def unique_sorted_values_plus_ALL(array):
    unique = array.unique().tolist()
    unique.sort()
    unique.insert(0, ALL)
    return unique

dropdown_region = widgets.Dropdown(options = unique_sorted_values_plus_ALL(metadata.region))

def dropdown_region_eventhandler(change):
    if (change.new == ALL):
        display(metadata)
    else:
        display(metadata[metadata.region == change.new])
        
dropdown_region.observe(dropdown_region_eventhandler, names='value')

ALL = 'All industries'
def unique_sorted_values_plus_ALL(array):
    unique = array.unique().tolist()
    unique.sort()
    unique.insert(0, ALL)
    return unique

dropdown_industry = widgets.Dropdown(options = unique_sorted_values_plus_ALL(metadata.industry))

def dropdown_industry_eventhandler(change):
    if (change.new == ALL):
        display(metadata)
    else:
        display(metadata[metadata.industry == change.new])
        
dropdown_industry.observe(dropdown_industry_eventhandler, names='value')

#display(dropdown_region)
#display(dropdown_industry)

def common_filtering(region, industry):
    output.clear_output()
    
    if (region == ALL) & (industry == ALL):
        common_filter = metadata
    elif (region == ALL):
        common_filter = metadata[metadata.industry == industry]
    elif (industry == ALL):
        common_filter = metadata[metadata.region == region]
    else:
        common_filter = metadata[(metadata.region == region) & 
                                  (metadata.industry == industry)]
    
    with output:
        display(common_filter)
        
def dropdown_region_eventhandler(change):
    common_filtering(dropdown_industry.value, change.new)
    
def dropdown_industry_eventhandler(change):
    common_filtering(change.new, dropdown_region.value)
    
dropdown_region.observe(dropdown_region_eventhandler, names='value')
dropdown_industry.observe(dropdown_industry_eventhandler, names='value')

input_widgets = widgets.HBox([dropdown_region, dropdown_industry])
#display(input_widgets)

df = pd.read_csv('mock_deal_database_1-2.csv')
df = df.rename(columns={'Industry Type': 'Industry_Type', 'Issuance Type': 'Issuance_Type'})

In [24]:
output = widgets.Output()

ALL = 'All issuance'
def unique_sorted_values_plus_ALL(array):
    unique = array.unique().tolist()
    unique.sort()
    unique.insert(0, ALL)
    return unique

dropdown_Issuance_Type = widgets.Dropdown(options = unique_sorted_values_plus_ALL(df.Issuance_Type))

def dropdown_Issuance_Type_eventhandler(change):
    if (change.new == ALL):
        display(df)
    else:
        display(df[df.Issuance_Type == change.new])
        
dropdown_Issuance_Type.observe(dropdown_Issuance_Type_eventhandler, names='value')

ALL = 'All industries'
def unique_sorted_values_plus_ALL(array):
    unique = array.unique().tolist()
    unique.sort()
    unique.insert(0, ALL)
    return unique

dropdown_Industry_Type = widgets.Dropdown(options = unique_sorted_values_plus_ALL(df.Industry_Type))

def dropdown_Industry_Type_eventhandler(change):
    if (change.new == ALL):
        display(df)
    else:
        display(df[df.Industry_Type == change.new])
        
dropdown_Industry_Type.observe(dropdown_Industry_Type_eventhandler, names='value')

#display(dropdown_region)
#display(dropdown_industry)

def common_filtering(Issuance_Type, Industry_Type):
    
    output.clear_output()
    
    if (Issuance_Type == ALL) & (Industry_Type == ALL):
        common_filter = df
    elif (Issuance_Type == ALL):
        common_filter = df[df.Industry_Type == Industry_Type]
    elif (Industry_Type == ALL):
        common_filter = df[df.Issuance_Type == Issuance_Type]
    else:
        common_filter = df[(df.Issuance_Type == Issuance_Type) & 
                                  (df.Industry_Type == Industry_Type)]
    
    with output:
        display(common_filter)
        
def dropdown_Issuance_Type_eventhandler(change):
    common_filtering(dropdown_Industry_Type.value, change.new)
    
def dropdown_Industry_Type_eventhandler(change):
    common_filtering(change.new, dropdown_Issuance_Type.value)
    
dropdown_Issuance_Type.observe(dropdown_Issuance_Type_eventhandler, names='value')
dropdown_Industry_Type.observe(dropdown_Industry_Type_eventhandler, names='value')

Input_widgets = widgets.HBox([dropdown_Issuance_Type, dropdown_Industry_Type])
#display(Input_widgets)

# Explore company database

In [25]:
tab = widgets.Tab([input_widgets, Input_widgets])
tab.set_title(0, 'Investor Filtering')
tab.set_title(1, 'Deal Filtering')
display(tab)
#df

Tab(children=(HBox(children=(Dropdown(options=('All regions', 'Alabama', 'Alaska', 'American Samoa', 'Arizona'â€¦

,investor,issuance_type,region,industry
8,CIRCUM,"['common stock', 'debt', 'investment fund']",Alabama,"['medtech', 'healthcare', 'venture capital']"
66,ORBOID,"['investment fund', 'debt']",Alabama,"['materials', 'technology']"
124,UTARA,"['debt', 'investment fund', 'equity']",Alabama,"['software', 'logistics', 'agriculture']"
182,ULTRIMAX,"['investment fund', 'investment fund', 'hardwa...",Alabama,"['construction', 'logistics', 'hardware']"
240,COREPAN,['investment fund'],Alabama,['logistics']
298,LUNCHPAD,"['investment fund', 'debt', 'equity']",Alabama,"['security', 'delivery', 'agriculture']"
356,AMTAS,"['investment fund', 'debt', 'convertible note']",Alabama,"['HR', 'delivery', 'foreign']"

In [21]:
#df

In [7]:
def normalize(amount_text):
    d = {
        'K': 1000,
        'M': 1000000,
        'B': 1000000000
    }
    if amount_text[-1] in d:
        # separate out the K, M, or B
        num, magnitude = amount_text[:-1], amount_text[-1]
        return int(float(num[1:]) * d[magnitude])
    else:
        return float(amount_text[1:])
    
df['Target Raise'] = df['Target Raise'].apply(lambda x: (normalize(x) if x != "n/a" else x))
df['Amount Raised'] = df['Amount Raised'].apply(lambda x: (normalize(x) if x != "n/a" else x))

print("Toggle your minimum preferred amount:\n")
@interact
def show_articles_more_than(column='Target Raise', Amount=100000000):
    return df.loc[df[column] > Amount]

Toggle your minimum preferred amount:

interactive(children=(Text(value='Target Raise', description='column'), IntSlider(value=100000000, descriptionâ€¦

In [8]:
# Parse the stringified features into their corresponding python objects
from ast import literal_eval

features = ['industry', 'issuance_type']
for feature in features:
    metadata[feature] = metadata[feature].apply(literal_eval)
    
# Function to convert all strings to lower case and strip names of spaces
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''
        
# Apply clean_data function to your features.
features = ['issuance_type', 'region', 'industry']

for feature in features:
    metadata[feature] = metadata[feature].apply(clean_data)
    
# Function to convert all strings to lower case and strip names of spaces
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''
        
# Apply clean_data function to your features.
features = ['issuance_type', 'region', 'industry']

for feature in features:
    metadata[feature] = metadata[feature].apply(clean_data)
    
def create_soup(x):
    return ' '.join(x['region']) + ' ' + ' '.join(x['issuance_type']) + ' ' + ' '.join(x['industry'])

metadata['soup'] = metadata.apply(create_soup, axis=1)

# Import CountVectorizer and create the count matrix
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(metadata['soup'])

# Compute the Cosine Similarity matrix based on the count_matrix
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(count_matrix, count_matrix)

# Reset index of your main DataFrame and construct reverse mapping as before
metadata = metadata.reset_index()
indices = pd.Series(metadata.index, index=metadata['investor'])

def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return ((metadata['investor'])).iloc[movie_indices]

# Reset index of your main DataFrame and construct reverse mapping as before
metadata = metadata.reset_index()
indices = pd.Series(metadata.index, index=metadata['investor'])

inv = input("Invited by (Admin/RRep/Issuer): ")
pref = input("Enter your preference: ")

max_count = 100

f = IntProgress(min=0, max=max_count) 
display(f) 

count = 0
while count <= max_count:
    f.value += 7 
    time.sleep(.1)
    count += 7

Invited by (Admin/RRep/Issuer): Jitin Jain
Enter your preference: ENTROFLEX

IntProgress(value=0)

In [11]:
bttn = widgets.Button(description='Similar Investors', button_style='primary')

def bttn_eventhandler(obj):
    print("Similar investors to" + ' ' + pref + ": \n")
    Placeholder = get_recommendations(pref, cosine_sim)
    placeholder = list(Placeholder)
    print(placeholder)

bttn.on_click(bttn_eventhandler)

btn1 = widgets.Button(description='Most Popular Deals', button_style='success')
btn = widgets.Button(description='Least Popular Deal', button_style='danger')
btn2 = widgets.Button(description='Viewed by Similar', button_style='warning')
btn3 = widgets.Button(description='Invested by Similar', button_style='info')
btn4 = widgets.Button(description='Invited by', button_style='primary')

def btn_eventhandler(obj):
    activity_ = pd.read_csv('Investor_Actions_Invested.csv')
    Hm = activity_['deals_invested'].value_counts().idxmin()
    print("Deal:" + '' + Hm)
    print("\n")
    print("No. of times invested:")
    ph = activity_['deals_invested'].value_counts().min()
    print(ph)
    print("\n.........................\n")
    
def btn4_eventhandler(obj):
    print("Invited by:" + ' ' + inv)
    print("\n.........................\n")
    
def btn1_eventhandler(obj):
    activity_ = pd.read_csv('Investor_Actions_Invested.csv')
    hm = activity_.deals_invested.mode()
    print(hm)
    print("\n")
    print("No. of times invested:")
    Ph = activity_['deals_invested'].value_counts().max()
    print(Ph)
    print("\n.........................\n")
    
def btn2_eventhandler(obj):
    activity = pd.read_csv('Investor_Actions_Viewed.csv')
    print("Deals Viewed by Investors similar to" + ' ' + pref + ": \n")
    Placeholder = get_recommendations(pref, cosine_sim)
    placeholder = list(Placeholder)
    heya = activity.loc[activity['investor'].isin(placeholder)]
    print(heya)
    
def btn3_eventhandler(obj):
    activity_ = pd.read_csv('Investor_Actions_Invested.csv')
    print("Deals Invested by Investors similar to" + ' ' + pref + ": \n")
    Placeholder = get_recommendations(pref, cosine_sim)
    placeholder = list(Placeholder)
    Heya = activity_.loc[activity_['investor'].isin(placeholder)]
    print(Heya)
    
btn.on_click(btn_eventhandler)
btn1.on_click(btn1_eventhandler)
btn2.on_click(btn2_eventhandler)
btn3.on_click(btn3_eventhandler)
btn4.on_click(btn4_eventhandler)


INput_widgets = widgets.HBox([btn1, btn, btn4])
INNput_widgets = widgets.HBox([bttn, btn2, btn3])

In [34]:
VBox([INput_widgets, INNput_widgets])

VBox(children=(HBox(children=(Button(button_style='success', description='Most Popular Deals', style=ButtonStyâ€¦

## JSON Transformation

In [21]:
new = pd.read_json(r'generated-4.json')
new

,_id,guid,actionperformed,ViewedIssuance,ViewedIssuance2,InvestedIssuance,download_common_documents,download_confidential_documents,sign_MNDA,age,name,company,email,phone,region,registered,targetraise,issuanceType
0,5f44212ac4b3119a6593907e,a0c49012-441e-47cc-9f36-f0c44968454d,Log In,Komp,Kale United,SnapStrat,True,False,False,48,Cotton Cook,BEZAL,cottoncook@bezal.com,+1 (956) 569-3908,California,2014-08-20T04:41:42 -08:00,$5954672,STO
1,5f44212a1481c8d8b6c888da,b86de82a-2c5d-4766-a5ab-54c02bcc8187,Indicate Issuance XYZ,CountablePro,EFF Ventures,Bozza,False,True,True,41,Dodson Barnes,ZYTRAX,dodsonbarnes@zytrax.com,+1 (879) 534-3832,New Mexico,2015-08-18T01:56:36 -08:00,$4456703,STO
2,5f44212aa5015a5a054ac78a,839a284c-f249-466a-b01a-874931fcebbe,Indicate Issuance XYZ,RoboMart,Automate,Vibing,False,False,True,33,Angelita Marks,GEOFORM,angelitamarks@geoform.com,+1 (839) 517-2966,Michigan,2018-04-21T05:30:12 -08:00,$3683550,equity
3,5f44212a2cda0df528234253,8cf79f9f-72dd-4877-a8c0-07ddcbb4fc8e,Indicate Issuance XYZ,KoinStreet,EFF Ventures,Vibbio,False,True,True,25,Bell Elliott,TOYLETRY,bellelliott@toyletry.com,+1 (993) 519-2575,Wisconsin,2019-06-20T01:50:35 -08:00,$3197952,equity
4,5f44212a232d6d3d46540604,29f192e7-8d77-478e-a249-9b898f259b94,Log In,BCASTER,Intercom,CountablePro,True,False,True,27,Sherri Tanner,KIGGLE,sherritanner@kiggle.com,+1 (872) 405-3484,Wyoming,2018-07-09T12:18:43 -08:00,$5134485,equity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,5f44212a4505ce90b9ac915a,10deee22-7de9-408b-b0b2-9e938229b170,View Issuance XYZ,Jenfi,Bozza,Vetchat,False,True,True,38,Eve Jacobson,BEZAL,evejacobson@bezal.com,+1 (810) 554-2719,North Dakota,2014-08-16T11:47:55 -08:00,$7289327,debt
998,5f44212a2fdc22bdf39b5beb,753f6c66-fcf3-4aa8-b5f2-38c70ac62803,Log In,KoinStreet,Vetchat,Kale United,False,False,True,44,Johnston Lowery,ZYTRAX,johnstonlowery@zytrax.com,+1 (885) 408-2439,Virgin Islands,2018-10-07T04:46:05 -08:00,$4466072,convertible note
999,5f44212a9810f4753de24d05,10fc8164-6947-4cc3-9afc-7b3a75fd2e5a,Indicate Issuance XYZ,SnapStrat,Securitize,Securitize,True,False,True,36,Grant Cook,GEOFORM,grantcook@geoform.com,+1 (918) 463-2816,Connecticut,2015-11-25T01:44:17 -08:00,$540198,convertible note
1000,5f44212a4f563a2cc9c2f0b4,5d575b5d-e73c-4fd3-b227-415c9653f5f4,Pass Issuance XYZ,Securitize,Bozza,AngioSlide,False,False,True,45,Coleen Barnes,TOYLETRY,coleenbarnes@toyletry.com,+1 (914) 561-3190,Nebraska,2015-10-19T10:30:24 -08:00,$6668862,equity
1001,5f44212a4a7b2faf02aa200c,a3dd10d1-71d5-418d-baad-fd7d4e4a1121,Indicate Issuance XYZ,Vibbio,Movie Coin,EFF Ventures,False,False,False,30,Margery Marks,KIGGLE,margerymarks@kiggle.com,+1 (810) 490-2174,Vermont,2015-11-07T06:01:00 -08:00,$3400566,convertible note

In [22]:
#Merge all issuances viewed/invested into one column
new['ViewedIssuance'] = new[['ViewedIssuance', 'ViewedIssuance2', 'InvestedIssuance']].agg(', '.join, axis=1)
#print only specific columns
clist = ['_id','company','ViewedIssuance','region','registered','issuanceType']
new = new[clist]
new

,_id,company,ViewedIssuance,region,registered,issuanceType
0,5f44212ac4b3119a6593907e,BEZAL,"Komp, Kale United, SnapStrat",California,2014-08-20T04:41:42 -08:00,STO
1,5f44212a1481c8d8b6c888da,ZYTRAX,"CountablePro, EFF Ventures, Bozza",New Mexico,2015-08-18T01:56:36 -08:00,STO
2,5f44212aa5015a5a054ac78a,GEOFORM,"RoboMart, Automate, Vibing",Michigan,2018-04-21T05:30:12 -08:00,equity
3,5f44212a2cda0df528234253,TOYLETRY,"KoinStreet, EFF Ventures, Vibbio",Wisconsin,2019-06-20T01:50:35 -08:00,equity
4,5f44212a232d6d3d46540604,KIGGLE,"BCASTER, Intercom, CountablePro",Wyoming,2018-07-09T12:18:43 -08:00,equity
...,...,...,...,...,...,...
997,5f44212a4505ce90b9ac915a,BEZAL,"Jenfi, Bozza, Vetchat",North Dakota,2014-08-16T11:47:55 -08:00,debt
998,5f44212a2fdc22bdf39b5beb,ZYTRAX,"KoinStreet, Vetchat, Kale United",Virgin Islands,2018-10-07T04:46:05 -08:00,convertible note
999,5f44212a9810f4753de24d05,GEOFORM,"SnapStrat, Securitize, Securitize",Connecticut,2015-11-25T01:44:17 -08:00,convertible note
1000,5f44212a4f563a2cc9c2f0b4,TOYLETRY,"Securitize, Bozza, AngioSlide",Nebraska,2015-10-19T10:30:24 -08:00,equity
1001,5f44212a4a7b2faf02aa200c,KIGGLE,"Vibbio, Movie Coin, EFF Ventures",Vermont,2015-11-07T06:01:00 -08:00,convertible note